version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cuyperpus_web
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/db_perpus
    command: sh -c "npx prisma migrate deploy && npx prisma db seed && pnpm start"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    container_name: cuyperpus_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_perpus
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
